version: "3"
services:
    app:
        build: .
        depends_on:
            - mariadb
        ports:
            - "8080:80"
        links:
            - mariadb:mariadb
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mariadb
            DB_PORT: 3306
            DB_DATABASE: dockerphp
            DB_USERNAME: root
            DB_PASSWORD: password
    mariadb:
        image: mariadb:10.1.21
        ports:
            - "13306:3306"
        environment:
            - MYSQL_DATABASE=dockerphp
            - MYSQL_ROOT_PASSWORD=password
